// lib/constants/modules.ts
// Konfigurasi semua modul FHIR yang tersedia

import type { ModuleInfo } from "../types/api";

export const FHIR_MODULES: ModuleInfo[] = [
  {
    name: "CarePlan",
    path: "/careplan",
    icon: "📋",
    desc: "Rencana perawatan pasien",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "ClinicalImpression",
    path: "/clinical-impression",
    icon: "🩺",
    desc: "Penilaian klinis pasien",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "Condition",
    path: "/condition",
    icon: "🏥",
    desc: "Kondisi & diagnosis",
    group: "Klinis",
    methods: ["POST", "GET", "PUT"],
    badge: "Active",
    hasPage: false,
  },
  {
    name: "Observation",
    path: "/observation",
    icon: "🔬",
    desc: "Hasil observasi & lab",
    group: "Klinis",
    methods: ["POST", "GET"],
    badge: "Active",
    hasPage: false,
  },
  {
    name: "Procedure",
    path: "/procedure",
    icon: "⚕️",
    desc: "Tindakan medis",
    group: "Klinis",
    methods: ["POST", "GET", "PUT"],
    badge: "Active",
    hasPage: false,
  },
  {
    name: "Encounter",
    path: "/encounter",
    icon: "🤝",
    desc: "Kunjungan pasien",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "Location",
    path: "/location",
    icon: "📍",
    desc: "Lokasi poli & ruangan",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "Patient",
    path: "/patient",
    icon: "👤",
    desc: "Data pasien",
    group: "Pasien & Praktisi",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "Practitioner",
    path: "/practitioner",
    icon: "👨‍⚕️",
    desc: "Data dokter",
    group: "Pasien & Praktisi",
    methods: ["POST", "GET", "PUT"],
    badge: "Active",
    hasPage: false,
  },
  {
    name: "Organization",
    path: "/organization",
    icon: "🏢",
    desc: "Data fasilitas",
    group: "Pasien & Praktisi",
    methods: ["GET"],
    badge: "Active",
    hasPage: false,
  },
  {
    name: "MedicationRequest",
    path: "/medication-request",
    icon: "💊",
    desc: "Resep obat",
    group: "Obat & Diagnosa",
    methods: ["POST", "GET"],
    badge: "Beta",
    hasPage: false,
  },
  {
    name: "AllergyIntolerance",
    path: "/allergy",
    icon: "⚠️",
    desc: "Alergi pasien",
    group: "Obat & Diagnosa",
    methods: ["POST", "GET"],
    badge: "Beta",
  },
  {
    name: "DiagnosticReport",
    path: "/diagnostic-report",
    icon: "📊",
    desc: "Laporan diagnostik",
    group: "Obat & Diagnosa",
    methods: ["POST", "GET"],
    badge: "Soon",
    hasPage: false,
  },
  {
    name: "ServiceRequest",
    path: "/service-request",
    icon: "🔬",
    desc: "Permintaan pemeriksaan radiologi",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "EpisodeOfCare",
    path: "/episode-of-care",
    icon: "📁",
    desc: "Episode perawatan pasien",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "QuestionnaireResponse",
    path: "/questionnaire-response",
    icon: "📝",
    desc: "Jawaban kuesioner klinis",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
];

export const MODULE_GROUPS = [
  "Klinis",
  "Pasien & Praktisi",
  "Obat & Diagnosa",
] as const;

export const METHOD_CONFIG = {
  GET: { label: "Ambil data", color: "blue" },
  POST: { label: "Buat baru", color: "emerald" },
  PUT: { label: "Perbarui penuh", color: "amber" },
  PATCH: { label: "Perbarui sebagian", color: "violet" },
  DELETE: { label: "Hapus data", color: "red" },
} as const;
