// lib/constants/modules.ts
// Konfigurasi semua modul FHIR yang tersedia

import type { ModuleInfo } from "../types/api";
import {
  LuClipboardList,
  LuStethoscope,
  LuActivity,
  LuFlaskConical,
  LuSyringe,
  LuHandshake,
  LuMapPin,
  LuUserRound,
  LuBriefcaseMedical,
  LuBuilding2,
  LuPill,
  LuTriangleAlert,
  LuScan,
  LuFileChartColumn,
  LuClipboardPlus,
  LuFolderOpen,
  LuClipboardCheck,
  LuImages,
  LuRadioTower,
  LuFilePenLine,
  LuTestTube,
} from "react-icons/lu";

export const FHIR_MODULES: ModuleInfo[] = [
  {
    name: "CarePlan",
    path: "/careplan",
    icon: LuClipboardList,
    desc: "Rencana perawatan pasien",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "ClinicalImpression",
    path: "/clinical-impression",
    icon: LuStethoscope,
    desc: "Penilaian klinis pasien",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "Condition",
    path: "/condition",
    icon: LuActivity,
    desc: "Kondisi & diagnosis",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "Observation",
    path: "/observation",
    icon: LuFlaskConical,
    desc: "Hasil observasi & lab",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "Procedure",
    path: "/procedure",
    icon: LuSyringe,
    desc: "Tindakan medis",
    group: "Klinis",
    methods: ["POST", "GET", "PUT"],
    badge: "Active",
    hasPage: false,
  },
  {
    name: "Encounter",
    path: "/encounter",
    icon: LuHandshake,
    desc: "Kunjungan pasien",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "Location",
    path: "/location",
    icon: LuMapPin,
    desc: "Lokasi poli & ruangan",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "Patient",
    path: "/patient",
    icon: LuUserRound,
    desc: "Data pasien",
    group: "Pasien & Praktisi",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "Practitioner",
    path: "/practitioner",
    icon: LuBriefcaseMedical,
    desc: "Data dokter",
    group: "Pasien & Praktisi",
    methods: ["GET"],
    badge: "Active",
  },
  {
    name: "Organization",
    path: "/organization",
    icon: LuBuilding2,
    desc: "Data fasilitas & departemen",
    group: "Pasien & Praktisi",
    methods: ["GET", "POST", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "MedicationRequest",
    path: "/medication-request",
    icon: LuPill,
    desc: "Resep obat",
    group: "Obat & Diagnosa",
    methods: ["POST", "GET"],
    badge: "Beta",
    hasPage: false,
  },
  {
    name: "AllergyIntolerance",
    path: "/allergy",
    icon: LuTriangleAlert,
    desc: "Alergi pasien",
    group: "Obat & Diagnosa",
    methods: ["POST", "GET"],
    badge: "Beta",
  },
  {
    name: "ImagingStudy",
    path: "/imaging-study",
    icon: LuScan,
    desc: "Pencarian studi pencitraan radiologi (DICOM)",
    group: "Klinis",
    methods: ["GET"],
    badge: "Active",
  },
  {
    name: "DiagnosticReport",
    path: "/diagnostic-report",
    icon: LuFileChartColumn,
    desc: "Laporan diagnostik",
    group: "Obat & Diagnosa",
    methods: ["POST", "GET"],
    badge: "Soon",
    hasPage: false,
  },
  {
    name: "ServiceRequest",
    path: "/service-request",
    icon: LuClipboardPlus,
    desc: "Permintaan pemeriksaan radiologi",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "Specimen",
    path: "/specimen",
    icon: LuTestTube,
    desc: "Spesimen laboratorium pasien",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "EpisodeOfCare",
    path: "/episode-of-care",
    icon: LuFolderOpen,
    desc: "Episode perawatan pasien",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "QuestionnaireResponse",
    path: "/questionnaire-response",
    icon: LuClipboardCheck,
    desc: "Jawaban kuesioner klinis",
    group: "Klinis",
    methods: ["POST", "GET", "PUT", "PATCH"],
    badge: "Active",
  },
  {
    name: "JpgToDicom",
    path: "/jpg-to-dcm",
    icon: LuImages,
    desc: "Konversi file JPG/JPEG ke format DICOM (CR Thorax PA)",
    group: "Utilitas",
    methods: [],
    badge: "Active",
  },
  {
    name: "DicomRouter",
    path: "/dicom-router",
    icon: LuRadioTower,
    desc: "Kirim file DICOM ke DICOM Router via storescu (DCMTK)",
    group: "Utilitas",
    methods: [],
    badge: "Active",
  },
  {
    name: "PatchAcsn",
    path: "/patch-acsn",
    icon: LuFilePenLine,
    desc: "Tambahkan atau ubah Accession Number pada file .dcm yang sudah ada",
    group: "Utilitas",
    methods: [],
    badge: "Active",
  },
];

export const MODULE_GROUPS = [
  "Klinis",
  "Pasien & Praktisi",
  "Obat & Diagnosa",
  "Utilitas",
] as const;

export const METHOD_CONFIG = {
  GET: { label: "Ambil data", color: "blue" },
  POST: { label: "Buat baru", color: "emerald" },
  PUT: { label: "Perbarui penuh", color: "amber" },
  PATCH: { label: "Perbarui sebagian", color: "violet" },
  DELETE: { label: "Hapus data", color: "red" },
} as const;
